// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQE1c9Lu8PaOPf-KA5WcHAicmVZZHRkY8',
    appId: '1:750631009032:web:5052cb44783f8aca93cabd',
    messagingSenderId: '750631009032',
    projectId: 'fin-tracker-pr',
    authDomain: 'fin-tracker-pr.firebaseapp.com',
    storageBucket: 'fin-tracker-pr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9WRPlhCOZxxlh8aWCJoWaksSzvqugmQ',
    appId: '1:750631009032:android:cd6fa9abc024a6b593cabd',
    messagingSenderId: '750631009032',
    projectId: 'fin-tracker-pr',
    storageBucket: 'fin-tracker-pr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsDiH2HSMi2xxZd0OiuBc9km5j7jFkOc',
    appId: '1:750631009032:ios:9e120e3f7e2c106f93cabd',
    messagingSenderId: '750631009032',
    projectId: 'fin-tracker-pr',
    storageBucket: 'fin-tracker-pr.firebasestorage.app',
    iosClientId: '750631009032-ad8t94kttu3n4sapndm102brc112v6e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsDiH2HSMi2xxZd0OiuBc9km5j7jFkOc',
    appId: '1:750631009032:ios:9e120e3f7e2c106f93cabd',
    messagingSenderId: '750631009032',
    projectId: 'fin-tracker-pr',
    storageBucket: 'fin-tracker-pr.firebasestorage.app',
    iosClientId: '750631009032-ad8t94kttu3n4sapndm102brc112v6e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQE1c9Lu8PaOPf-KA5WcHAicmVZZHRkY8',
    appId: '1:750631009032:web:1149235d607fcf6293cabd',
    messagingSenderId: '750631009032',
    projectId: 'fin-tracker-pr',
    authDomain: 'fin-tracker-pr.firebaseapp.com',
    storageBucket: 'fin-tracker-pr.firebasestorage.app',
  );

}